[package]
name = "mechon"
version.workspace = true
edition.workspace = true

[[bin]]
name = "mechon"
path = "src/main.rs"

[dependencies]
mechon-types = { workspace = true }

tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
anyhow = { workspace = true }

clap = { workspace = true }
reqwest = { workspace = true }
indicatif = { workspace = true }
dirs = { workspace = true }
colored = { workspace = true }
zip = "2"
