// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (user_id, name, prefix, hash, scopes, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, name, prefix, hash, scopes, last_used_at, expires_at, created_at
`

type CreateAPIKeyParams struct {
	UserID    uuid.UUID
	Name      string
	Prefix    string
	Hash      []byte
	Scopes    []string
	ExpiresAt *time.Time
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.UserID,
		arg.Name,
		arg.Prefix,
		arg.Hash,
		arg.Scopes,
		arg.ExpiresAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.Hash,
		&i.Scopes,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :execrows
DELETE FROM api_keys WHERE id = $1 AND user_id = $2
`

type DeleteAPIKeyParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteAPIKey(ctx context.Context, arg DeleteAPIKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAPIKey, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAPIKeyUser = `-- name: GetAPIKeyUser :one
SELECT users.id, users.email, users.name, users.password_hash, users.role, users.external_id, users.suspended_at, users.created_at, api_keys.id AS key_id, api_keys.scopes, api_keys.last_used_at
FROM api_keys
JOIN users ON users.id = api_keys.user_id
WHERE api_keys.hash = $1 AND (api_keys.expires_at IS NULL OR api_keys.expires_at > now())
`

type GetAPIKeyUserRow struct {
	User       User
	KeyID      uuid.UUID
	Scopes     []string
	LastUsedAt *time.Time
}

func (q *Queries) GetAPIKeyUser(ctx context.Context, hash []byte) (GetAPIKeyUserRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyUser, hash)
	var i GetAPIKeyUserRow
	err := row.Scan(
		&i.User.ID,
		&i.User.Email,
		&i.User.Name,
		&i.User.PasswordHash,
		&i.User.Role,
		&i.User.ExternalID,
		&i.User.SuspendedAt,
		&i.User.CreatedAt,
		&i.KeyID,
		&i.Scopes,
		&i.LastUsedAt,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, user_id, name, prefix, hash, scopes, last_used_at, expires_at, created_at FROM api_keys WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeys(ctx context.Context, userID uuid.UUID) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Prefix,
			&i.Hash,
			&i.Scopes,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchAPIKey = `-- name: TouchAPIKey :exec
UPDATE api_keys SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchAPIKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAPIKey, id)
	return err
}
