// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getSetting = `-- name: GetSetting :one
SELECT value FROM settings WHERE key = $1
`

func (q *Queries) GetSetting(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRow(ctx, getSetting, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const insertAudit = `-- name: InsertAudit :exec
INSERT INTO audit_log (actor_id, actor_name, via_api_key, action, target_type, target_id, target_name, metadata, ip)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertAuditParams struct {
	ActorID    *uuid.UUID
	ActorName  string
	ViaApiKey  bool
	Action     string
	TargetType string
	TargetID   string
	TargetName string
	Metadata   []byte
	Ip         string
}

func (q *Queries) InsertAudit(ctx context.Context, arg InsertAuditParams) error {
	_, err := q.db.Exec(ctx, insertAudit,
		arg.ActorID,
		arg.ActorName,
		arg.ViaApiKey,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.TargetName,
		arg.Metadata,
		arg.Ip,
	)
	return err
}

const listAudit = `-- name: ListAudit :many
SELECT id, actor_id, actor_name, via_api_key, action, target_type, target_id, target_name, metadata, ip, created_at FROM audit_log
WHERE ($1::bigint IS NULL OR id < $1)
  AND ($2::text = '' OR action LIKE $2::text || '%')
ORDER BY id DESC
LIMIT 100
`

type ListAuditParams struct {
	Before *int64
	Prefix string
}

func (q *Queries) ListAudit(ctx context.Context, arg ListAuditParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAudit, arg.Before, arg.Prefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.ActorName,
			&i.ViaApiKey,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.TargetName,
			&i.Metadata,
			&i.Ip,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSettings = `-- name: ListSettings :many
SELECT key, value FROM settings
`

type ListSettingsRow struct {
	Key   string
	Value string
}

func (q *Queries) ListSettings(ctx context.Context) ([]ListSettingsRow, error) {
	rows, err := q.db.Query(ctx, listSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSettingsRow
	for rows.Next() {
		var i ListSettingsRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putSetting = `-- name: PutSetting :exec
INSERT INTO settings (key, value) VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE SET value = excluded.value, updated_at = now()
`

type PutSettingParams struct {
	Key   string
	Value string
}

func (q *Queries) PutSetting(ctx context.Context, arg PutSettingParams) error {
	_, err := q.db.Exec(ctx, putSetting, arg.Key, arg.Value)
	return err
}
