// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bots.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countBotsByState = `-- name: CountBotsByState :many
SELECT observed_state, count(*)::int AS n FROM bots WHERE deleted_at IS NULL GROUP BY observed_state
`

type CountBotsByStateRow struct {
	ObservedState BotObservedState
	N             int32
}

func (q *Queries) CountBotsByState(ctx context.Context) ([]CountBotsByStateRow, error) {
	rows, err := q.db.Query(ctx, countBotsByState)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountBotsByStateRow
	for rows.Next() {
		var i CountBotsByStateRow
		if err := rows.Scan(&i.ObservedState, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createBot = `-- name: CreateBot :one
INSERT INTO bots (subscription_id, node_id, name, template, memory_mb, cpu_millicores, disk_mb)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, uid_seq, subscription_id, node_id, name, template, memory_mb, cpu_millicores, disk_mb, desired_state, observed_state, observed_error, exit_code, current_deploy_id, restart_count, state_changed_at, created_at, deleted_at
`

type CreateBotParams struct {
	SubscriptionID uuid.UUID
	NodeID         uuid.UUID
	Name           string
	Template       string
	MemoryMb       int32
	CpuMillicores  int32
	DiskMb         int32
}

func (q *Queries) CreateBot(ctx context.Context, arg CreateBotParams) (Bot, error) {
	row := q.db.QueryRow(ctx, createBot,
		arg.SubscriptionID,
		arg.NodeID,
		arg.Name,
		arg.Template,
		arg.MemoryMb,
		arg.CpuMillicores,
		arg.DiskMb,
	)
	var i Bot
	err := row.Scan(
		&i.ID,
		&i.UidSeq,
		&i.SubscriptionID,
		&i.NodeID,
		&i.Name,
		&i.Template,
		&i.MemoryMb,
		&i.CpuMillicores,
		&i.DiskMb,
		&i.DesiredState,
		&i.ObservedState,
		&i.ObservedError,
		&i.ExitCode,
		&i.CurrentDeployID,
		&i.RestartCount,
		&i.StateChangedAt,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getBot = `-- name: GetBot :one
SELECT bots.id, bots.uid_seq, bots.subscription_id, bots.node_id, bots.name, bots.template, bots.memory_mb, bots.cpu_millicores, bots.disk_mb, bots.desired_state, bots.observed_state, bots.observed_error, bots.exit_code, bots.current_deploy_id, bots.restart_count, bots.state_changed_at, bots.created_at, bots.deleted_at, subscriptions.user_id AS owner_id, subscriptions.status AS subscription_status,
       plans.pids_max, plans.hardened, plans.name AS plan_name, nodes.name AS node_name,
       users.name AS owner_name, users.email AS owner_email
FROM bots
JOIN subscriptions ON subscriptions.id = bots.subscription_id
JOIN users ON users.id = subscriptions.user_id
JOIN plans ON plans.id = subscriptions.plan_id
JOIN nodes ON nodes.id = bots.node_id
WHERE bots.id = $1 AND bots.deleted_at IS NULL
`

type GetBotRow struct {
	Bot                Bot
	OwnerID            uuid.UUID
	SubscriptionStatus SubscriptionStatus
	PidsMax            int32
	Hardened           bool
	PlanName           string
	NodeName           string
	OwnerName          string
	OwnerEmail         string
}

func (q *Queries) GetBot(ctx context.Context, id uuid.UUID) (GetBotRow, error) {
	row := q.db.QueryRow(ctx, getBot, id)
	var i GetBotRow
	err := row.Scan(
		&i.Bot.ID,
		&i.Bot.UidSeq,
		&i.Bot.SubscriptionID,
		&i.Bot.NodeID,
		&i.Bot.Name,
		&i.Bot.Template,
		&i.Bot.MemoryMb,
		&i.Bot.CpuMillicores,
		&i.Bot.DiskMb,
		&i.Bot.DesiredState,
		&i.Bot.ObservedState,
		&i.Bot.ObservedError,
		&i.Bot.ExitCode,
		&i.Bot.CurrentDeployID,
		&i.Bot.RestartCount,
		&i.Bot.StateChangedAt,
		&i.Bot.CreatedAt,
		&i.Bot.DeletedAt,
		&i.OwnerID,
		&i.SubscriptionStatus,
		&i.PidsMax,
		&i.Hardened,
		&i.PlanName,
		&i.NodeName,
		&i.OwnerName,
		&i.OwnerEmail,
	)
	return i, err
}

const getBotSpec = `-- name: GetBotSpec :one
SELECT bots.id, bots.uid_seq, bots.subscription_id, bots.node_id, bots.name, bots.template, bots.memory_mb, bots.cpu_millicores, bots.disk_mb, bots.desired_state, bots.observed_state, bots.observed_error, bots.exit_code, bots.current_deploy_id, bots.restart_count, bots.state_changed_at, bots.created_at, bots.deleted_at, coalesce(subscriptions.pids_max, plans.pids_max)::int AS pids_max, plans.hardened,
       subscriptions.status AS subscription_status,
       (users.suspended_at IS NOT NULL)::bool AS owner_suspended, deploys.artifact_sha256
FROM bots
JOIN subscriptions ON subscriptions.id = bots.subscription_id
JOIN users ON users.id = subscriptions.user_id
JOIN plans ON plans.id = subscriptions.plan_id
LEFT JOIN deploys ON deploys.id = bots.current_deploy_id
WHERE bots.id = $1
`

type GetBotSpecRow struct {
	Bot                Bot
	PidsMax            int32
	Hardened           bool
	SubscriptionStatus SubscriptionStatus
	OwnerSuspended     bool
	ArtifactSha256     *string
}

func (q *Queries) GetBotSpec(ctx context.Context, id uuid.UUID) (GetBotSpecRow, error) {
	row := q.db.QueryRow(ctx, getBotSpec, id)
	var i GetBotSpecRow
	err := row.Scan(
		&i.Bot.ID,
		&i.Bot.UidSeq,
		&i.Bot.SubscriptionID,
		&i.Bot.NodeID,
		&i.Bot.Name,
		&i.Bot.Template,
		&i.Bot.MemoryMb,
		&i.Bot.CpuMillicores,
		&i.Bot.DiskMb,
		&i.Bot.DesiredState,
		&i.Bot.ObservedState,
		&i.Bot.ObservedError,
		&i.Bot.ExitCode,
		&i.Bot.CurrentDeployID,
		&i.Bot.RestartCount,
		&i.Bot.StateChangedAt,
		&i.Bot.CreatedAt,
		&i.Bot.DeletedAt,
		&i.PidsMax,
		&i.Hardened,
		&i.SubscriptionStatus,
		&i.OwnerSuspended,
		&i.ArtifactSha256,
	)
	return i, err
}

const listBots = `-- name: ListBots :many
SELECT bots.id, bots.uid_seq, bots.subscription_id, bots.node_id, bots.name, bots.template, bots.memory_mb, bots.cpu_millicores, bots.disk_mb, bots.desired_state, bots.observed_state, bots.observed_error, bots.exit_code, bots.current_deploy_id, bots.restart_count, bots.state_changed_at, bots.created_at, bots.deleted_at, subscriptions.user_id AS owner_id, users.name AS owner_name, users.email AS owner_email,
       nodes.name AS node_name, plans.name AS plan_name
FROM bots
JOIN subscriptions ON subscriptions.id = bots.subscription_id
JOIN users ON users.id = subscriptions.user_id
JOIN plans ON plans.id = subscriptions.plan_id
JOIN nodes ON nodes.id = bots.node_id
WHERE bots.deleted_at IS NULL
  AND ($1::uuid IS NULL OR subscriptions.user_id = $1)
ORDER BY bots.created_at DESC
`

type ListBotsRow struct {
	Bot        Bot
	OwnerID    uuid.UUID
	OwnerName  string
	OwnerEmail string
	NodeName   string
	PlanName   string
}

func (q *Queries) ListBots(ctx context.Context, ownerID *uuid.UUID) ([]ListBotsRow, error) {
	rows, err := q.db.Query(ctx, listBots, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBotsRow
	for rows.Next() {
		var i ListBotsRow
		if err := rows.Scan(
			&i.Bot.ID,
			&i.Bot.UidSeq,
			&i.Bot.SubscriptionID,
			&i.Bot.NodeID,
			&i.Bot.Name,
			&i.Bot.Template,
			&i.Bot.MemoryMb,
			&i.Bot.CpuMillicores,
			&i.Bot.DiskMb,
			&i.Bot.DesiredState,
			&i.Bot.ObservedState,
			&i.Bot.ObservedError,
			&i.Bot.ExitCode,
			&i.Bot.CurrentDeployID,
			&i.Bot.RestartCount,
			&i.Bot.StateChangedAt,
			&i.Bot.CreatedAt,
			&i.Bot.DeletedAt,
			&i.OwnerID,
			&i.OwnerName,
			&i.OwnerEmail,
			&i.NodeName,
			&i.PlanName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeBotSpecs = `-- name: ListNodeBotSpecs :many
SELECT bots.id, bots.uid_seq, bots.subscription_id, bots.node_id, bots.name, bots.template, bots.memory_mb, bots.cpu_millicores, bots.disk_mb, bots.desired_state, bots.observed_state, bots.observed_error, bots.exit_code, bots.current_deploy_id, bots.restart_count, bots.state_changed_at, bots.created_at, bots.deleted_at, coalesce(subscriptions.pids_max, plans.pids_max)::int AS pids_max, plans.hardened,
       subscriptions.status AS subscription_status,
       (users.suspended_at IS NOT NULL)::bool AS owner_suspended, deploys.artifact_sha256
FROM bots
JOIN subscriptions ON subscriptions.id = bots.subscription_id
JOIN users ON users.id = subscriptions.user_id
JOIN plans ON plans.id = subscriptions.plan_id
LEFT JOIN deploys ON deploys.id = bots.current_deploy_id
WHERE bots.node_id = $1 AND bots.deleted_at IS NULL
`

type ListNodeBotSpecsRow struct {
	Bot                Bot
	PidsMax            int32
	Hardened           bool
	SubscriptionStatus SubscriptionStatus
	OwnerSuspended     bool
	ArtifactSha256     *string
}

// Everything the panel needs to build the specs for one node's sync.
func (q *Queries) ListNodeBotSpecs(ctx context.Context, nodeID uuid.UUID) ([]ListNodeBotSpecsRow, error) {
	rows, err := q.db.Query(ctx, listNodeBotSpecs, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNodeBotSpecsRow
	for rows.Next() {
		var i ListNodeBotSpecsRow
		if err := rows.Scan(
			&i.Bot.ID,
			&i.Bot.UidSeq,
			&i.Bot.SubscriptionID,
			&i.Bot.NodeID,
			&i.Bot.Name,
			&i.Bot.Template,
			&i.Bot.MemoryMb,
			&i.Bot.CpuMillicores,
			&i.Bot.DiskMb,
			&i.Bot.DesiredState,
			&i.Bot.ObservedState,
			&i.Bot.ObservedError,
			&i.Bot.ExitCode,
			&i.Bot.CurrentDeployID,
			&i.Bot.RestartCount,
			&i.Bot.StateChangedAt,
			&i.Bot.CreatedAt,
			&i.Bot.DeletedAt,
			&i.PidsMax,
			&i.Hardened,
			&i.SubscriptionStatus,
			&i.OwnerSuspended,
			&i.ArtifactSha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlanBotIDs = `-- name: ListPlanBotIDs :many
SELECT bots.id FROM bots JOIN subscriptions ON subscriptions.id = bots.subscription_id
WHERE subscriptions.plan_id = $1 AND bots.deleted_at IS NULL
`

func (q *Queries) ListPlanBotIDs(ctx context.Context, planID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listPlanBotIDs, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionBotIDs = `-- name: ListSubscriptionBotIDs :many
SELECT id FROM bots WHERE subscription_id = $1 AND deleted_at IS NULL
`

func (q *Queries) ListSubscriptionBotIDs(ctx context.Context, subscriptionID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listSubscriptionBotIDs, subscriptionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserBotIDs = `-- name: ListUserBotIDs :many
SELECT bots.id, bots.node_id FROM bots
JOIN subscriptions ON subscriptions.id = bots.subscription_id
WHERE subscriptions.user_id = $1 AND bots.deleted_at IS NULL
`

type ListUserBotIDsRow struct {
	ID     uuid.UUID
	NodeID uuid.UUID
}

func (q *Queries) ListUserBotIDs(ctx context.Context, userID uuid.UUID) ([]ListUserBotIDsRow, error) {
	rows, err := q.db.Query(ctx, listUserBotIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserBotIDsRow
	for rows.Next() {
		var i ListUserBotIDsRow
		if err := rows.Scan(&i.ID, &i.NodeID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNodeBotsUnknown = `-- name: MarkNodeBotsUnknown :exec
UPDATE bots SET observed_state = 'unknown', state_changed_at = now()
WHERE node_id = $1 AND deleted_at IS NULL AND observed_state <> 'unknown'
`

func (q *Queries) MarkNodeBotsUnknown(ctx context.Context, nodeID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markNodeBotsUnknown, nodeID)
	return err
}

const setBotCurrentDeploy = `-- name: SetBotCurrentDeploy :exec
UPDATE bots SET current_deploy_id = $2 WHERE id = $1
`

type SetBotCurrentDeployParams struct {
	ID              uuid.UUID
	CurrentDeployID *uuid.UUID
}

func (q *Queries) SetBotCurrentDeploy(ctx context.Context, arg SetBotCurrentDeployParams) error {
	_, err := q.db.Exec(ctx, setBotCurrentDeploy, arg.ID, arg.CurrentDeployID)
	return err
}

const setBotDesired = `-- name: SetBotDesired :exec
UPDATE bots SET desired_state = $2 WHERE id = $1
`

type SetBotDesiredParams struct {
	ID           uuid.UUID
	DesiredState BotDesiredState
}

func (q *Queries) SetBotDesired(ctx context.Context, arg SetBotDesiredParams) error {
	_, err := q.db.Exec(ctx, setBotDesired, arg.ID, arg.DesiredState)
	return err
}

const setBotObserved = `-- name: SetBotObserved :exec
UPDATE bots SET observed_state = $1::bot_observed_state, observed_error = $2,
                exit_code = $3, restart_count = $4,
                state_changed_at = CASE WHEN observed_state <> $1::bot_observed_state THEN now() ELSE state_changed_at END
WHERE id = $5
`

type SetBotObservedParams struct {
	ObservedState BotObservedState
	ObservedError string
	ExitCode      *int32
	RestartCount  int32
	ID            uuid.UUID
}

func (q *Queries) SetBotObserved(ctx context.Context, arg SetBotObservedParams) error {
	_, err := q.db.Exec(ctx, setBotObserved,
		arg.ObservedState,
		arg.ObservedError,
		arg.ExitCode,
		arg.RestartCount,
		arg.ID,
	)
	return err
}

const setBotsDesiredForSubscription = `-- name: SetBotsDesiredForSubscription :many
UPDATE bots SET desired_state = $2 WHERE subscription_id = $1 AND deleted_at IS NULL RETURNING id, node_id
`

type SetBotsDesiredForSubscriptionParams struct {
	SubscriptionID uuid.UUID
	DesiredState   BotDesiredState
}

type SetBotsDesiredForSubscriptionRow struct {
	ID     uuid.UUID
	NodeID uuid.UUID
}

func (q *Queries) SetBotsDesiredForSubscription(ctx context.Context, arg SetBotsDesiredForSubscriptionParams) ([]SetBotsDesiredForSubscriptionRow, error) {
	rows, err := q.db.Query(ctx, setBotsDesiredForSubscription, arg.SubscriptionID, arg.DesiredState)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SetBotsDesiredForSubscriptionRow
	for rows.Next() {
		var i SetBotsDesiredForSubscriptionRow
		if err := rows.Scan(&i.ID, &i.NodeID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteBot = `-- name: SoftDeleteBot :exec
UPDATE bots SET deleted_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteBot(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteBot, id)
	return err
}

const updateBotSettings = `-- name: UpdateBotSettings :one
UPDATE bots SET name = $2, memory_mb = $3, cpu_millicores = $4, disk_mb = $5
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, uid_seq, subscription_id, node_id, name, template, memory_mb, cpu_millicores, disk_mb, desired_state, observed_state, observed_error, exit_code, current_deploy_id, restart_count, state_changed_at, created_at, deleted_at
`

type UpdateBotSettingsParams struct {
	ID            uuid.UUID
	Name          string
	MemoryMb      int32
	CpuMillicores int32
	DiskMb        int32
}

func (q *Queries) UpdateBotSettings(ctx context.Context, arg UpdateBotSettingsParams) (Bot, error) {
	row := q.db.QueryRow(ctx, updateBotSettings,
		arg.ID,
		arg.Name,
		arg.MemoryMb,
		arg.CpuMillicores,
		arg.DiskMb,
	)
	var i Bot
	err := row.Scan(
		&i.ID,
		&i.UidSeq,
		&i.SubscriptionID,
		&i.NodeID,
		&i.Name,
		&i.Template,
		&i.MemoryMb,
		&i.CpuMillicores,
		&i.DiskMb,
		&i.DesiredState,
		&i.ObservedState,
		&i.ObservedError,
		&i.ExitCode,
		&i.CurrentDeployID,
		&i.RestartCount,
		&i.StateChangedAt,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
