// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deploys.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const appendDeployLog = `-- name: AppendDeployLog :exec
UPDATE deploys SET log = right(log || $2, 200000) WHERE id = $1
`

type AppendDeployLogParams struct {
	ID  uuid.UUID
	Log string
}

func (q *Queries) AppendDeployLog(ctx context.Context, arg AppendDeployLogParams) error {
	_, err := q.db.Exec(ctx, appendDeployLog, arg.ID, arg.Log)
	return err
}

const createDeploy = `-- name: CreateDeploy :one
INSERT INTO deploys (bot_id, number, source, git_url, git_ref, git_commit, rollback_of, artifact_sha256, artifact_bytes, created_by)
VALUES ($1, (SELECT coalesce(max(number), 0) + 1 FROM deploys d WHERE d.bot_id = $1),
        $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, bot_id, number, source, git_url, git_ref, git_commit, rollback_of, artifact_sha256, artifact_bytes, status, error, log, created_by, created_at, finished_at
`

type CreateDeployParams struct {
	BotID          uuid.UUID
	Source         DeploySource
	GitUrl         string
	GitRef         string
	GitCommit      string
	RollbackOf     *uuid.UUID
	ArtifactSha256 string
	ArtifactBytes  int64
	CreatedBy      *uuid.UUID
}

func (q *Queries) CreateDeploy(ctx context.Context, arg CreateDeployParams) (Deploy, error) {
	row := q.db.QueryRow(ctx, createDeploy,
		arg.BotID,
		arg.Source,
		arg.GitUrl,
		arg.GitRef,
		arg.GitCommit,
		arg.RollbackOf,
		arg.ArtifactSha256,
		arg.ArtifactBytes,
		arg.CreatedBy,
	)
	var i Deploy
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.Number,
		&i.Source,
		&i.GitUrl,
		&i.GitRef,
		&i.GitCommit,
		&i.RollbackOf,
		&i.ArtifactSha256,
		&i.ArtifactBytes,
		&i.Status,
		&i.Error,
		&i.Log,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const deployBelongsToNode = `-- name: DeployBelongsToNode :one
SELECT deploys.artifact_sha256 FROM deploys
JOIN bots ON bots.id = deploys.bot_id
WHERE deploys.id = $1 AND bots.node_id = $2 AND bots.deleted_at IS NULL
`

type DeployBelongsToNodeParams struct {
	ID     uuid.UUID
	NodeID uuid.UUID
}

func (q *Queries) DeployBelongsToNode(ctx context.Context, arg DeployBelongsToNodeParams) (string, error) {
	row := q.db.QueryRow(ctx, deployBelongsToNode, arg.ID, arg.NodeID)
	var artifact_sha256 string
	err := row.Scan(&artifact_sha256)
	return artifact_sha256, err
}

const getDeploy = `-- name: GetDeploy :one
SELECT id, bot_id, number, source, git_url, git_ref, git_commit, rollback_of, artifact_sha256, artifact_bytes, status, error, log, created_by, created_at, finished_at FROM deploys WHERE id = $1
`

func (q *Queries) GetDeploy(ctx context.Context, id uuid.UUID) (Deploy, error) {
	row := q.db.QueryRow(ctx, getDeploy, id)
	var i Deploy
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.Number,
		&i.Source,
		&i.GitUrl,
		&i.GitRef,
		&i.GitCommit,
		&i.RollbackOf,
		&i.ArtifactSha256,
		&i.ArtifactBytes,
		&i.Status,
		&i.Error,
		&i.Log,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const lastLiveDeploy = `-- name: LastLiveDeploy :one
SELECT id FROM deploys WHERE bot_id = $1 AND status = 'live' ORDER BY number DESC LIMIT 1
`

func (q *Queries) LastLiveDeploy(ctx context.Context, botID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lastLiveDeploy, botID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listDeploys = `-- name: ListDeploys :many
SELECT deploys.id, deploys.bot_id, deploys.number, deploys.source, deploys.git_url, deploys.git_ref, deploys.git_commit, deploys.rollback_of, deploys.artifact_sha256, deploys.artifact_bytes, deploys.status, deploys.error, deploys.log, deploys.created_by, deploys.created_at, deploys.finished_at, users.name AS created_by_name
FROM deploys LEFT JOIN users ON users.id = deploys.created_by
WHERE bot_id = $1
ORDER BY number DESC
LIMIT 50
`

type ListDeploysRow struct {
	ID             uuid.UUID
	BotID          uuid.UUID
	Number         int32
	Source         DeploySource
	GitUrl         string
	GitRef         string
	GitCommit      string
	RollbackOf     *uuid.UUID
	ArtifactSha256 string
	ArtifactBytes  int64
	Status         DeployStatus
	Error          string
	Log            string
	CreatedBy      *uuid.UUID
	CreatedAt      time.Time
	FinishedAt     *time.Time
	CreatedByName  *string
}

func (q *Queries) ListDeploys(ctx context.Context, botID uuid.UUID) ([]ListDeploysRow, error) {
	rows, err := q.db.Query(ctx, listDeploys, botID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDeploysRow
	for rows.Next() {
		var i ListDeploysRow
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.Number,
			&i.Source,
			&i.GitUrl,
			&i.GitRef,
			&i.GitCommit,
			&i.RollbackOf,
			&i.ArtifactSha256,
			&i.ArtifactBytes,
			&i.Status,
			&i.Error,
			&i.Log,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.FinishedAt,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDeployStatus = `-- name: SetDeployStatus :exec
UPDATE deploys SET status = $1::deploy_status, error = $2,
                   finished_at = CASE WHEN $1::deploy_status IN ('live', 'failed', 'superseded') THEN now() ELSE finished_at END
WHERE id = $3
`

type SetDeployStatusParams struct {
	Status DeployStatus
	Error  string
	ID     uuid.UUID
}

func (q *Queries) SetDeployStatus(ctx context.Context, arg SetDeployStatusParams) error {
	_, err := q.db.Exec(ctx, setDeployStatus, arg.Status, arg.Error, arg.ID)
	return err
}

const supersedeLiveDeploys = `-- name: SupersedeLiveDeploys :exec
UPDATE deploys SET status = 'superseded'
WHERE bot_id = $1 AND id <> $2 AND status = 'live'
`

type SupersedeLiveDeploysParams struct {
	BotID uuid.UUID
	ID    uuid.UUID
}

func (q *Queries) SupersedeLiveDeploys(ctx context.Context, arg SupersedeLiveDeploysParams) error {
	_, err := q.db.Exec(ctx, supersedeLiveDeploys, arg.BotID, arg.ID)
	return err
}

const supersedePendingDeploys = `-- name: SupersedePendingDeploys :exec
UPDATE deploys SET status = 'superseded', finished_at = now()
WHERE bot_id = $1 AND id <> $2 AND status IN ('queued', 'fetching', 'installing')
`

type SupersedePendingDeploysParams struct {
	BotID uuid.UUID
	ID    uuid.UUID
}

func (q *Queries) SupersedePendingDeploys(ctx context.Context, arg SupersedePendingDeploysParams) error {
	_, err := q.db.Exec(ctx, supersedePendingDeploys, arg.BotID, arg.ID)
	return err
}
