// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: env.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteBotEnv = `-- name: DeleteBotEnv :exec
DELETE FROM bot_env WHERE bot_id = $1
`

func (q *Queries) DeleteBotEnv(ctx context.Context, botID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBotEnv, botID)
	return err
}

const insertBotEnv = `-- name: InsertBotEnv :exec
INSERT INTO bot_env (bot_id, key, value_enc, secret) VALUES ($1, $2, $3, $4)
`

type InsertBotEnvParams struct {
	BotID    uuid.UUID
	Key      string
	ValueEnc []byte
	Secret   bool
}

func (q *Queries) InsertBotEnv(ctx context.Context, arg InsertBotEnvParams) error {
	_, err := q.db.Exec(ctx, insertBotEnv,
		arg.BotID,
		arg.Key,
		arg.ValueEnc,
		arg.Secret,
	)
	return err
}

const listBotEnv = `-- name: ListBotEnv :many
SELECT bot_id, key, value_enc, secret FROM bot_env WHERE bot_id = $1 ORDER BY key
`

func (q *Queries) ListBotEnv(ctx context.Context, botID uuid.UUID) ([]BotEnv, error) {
	rows, err := q.db.Query(ctx, listBotEnv, botID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotEnv
	for rows.Next() {
		var i BotEnv
		if err := rows.Scan(
			&i.BotID,
			&i.Key,
			&i.ValueEnc,
			&i.Secret,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
