// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metrics.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteOldMetrics = `-- name: DeleteOldMetrics :execrows
DELETE FROM bot_metrics WHERE ts < $1
`

func (q *Queries) DeleteOldMetrics(ctx context.Context, ts time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldMetrics, ts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listBotMetrics = `-- name: ListBotMetrics :many
SELECT ts, cpu_pct, memory_bytes, disk_bytes FROM bot_metrics
WHERE bot_id = $1 AND ts >= $2
ORDER BY ts
`

type ListBotMetricsParams struct {
	BotID uuid.UUID
	Ts    time.Time
}

type ListBotMetricsRow struct {
	Ts          time.Time
	CpuPct      float32
	MemoryBytes int64
	DiskBytes   int64
}

func (q *Queries) ListBotMetrics(ctx context.Context, arg ListBotMetricsParams) ([]ListBotMetricsRow, error) {
	rows, err := q.db.Query(ctx, listBotMetrics, arg.BotID, arg.Ts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBotMetricsRow
	for rows.Next() {
		var i ListBotMetricsRow
		if err := rows.Scan(
			&i.Ts,
			&i.CpuPct,
			&i.MemoryBytes,
			&i.DiskBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBotMetric = `-- name: UpsertBotMetric :exec
INSERT INTO bot_metrics (bot_id, ts, cpu_pct, memory_bytes, disk_bytes, net_rx, net_tx)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (bot_id, ts) DO UPDATE
SET cpu_pct = excluded.cpu_pct, memory_bytes = excluded.memory_bytes, disk_bytes = excluded.disk_bytes,
    net_rx = excluded.net_rx, net_tx = excluded.net_tx
`

type UpsertBotMetricParams struct {
	BotID       uuid.UUID
	Ts          time.Time
	CpuPct      float32
	MemoryBytes int64
	DiskBytes   int64
	NetRx       int64
	NetTx       int64
}

func (q *Queries) UpsertBotMetric(ctx context.Context, arg UpsertBotMetricParams) error {
	_, err := q.db.Exec(ctx, upsertBotMetric,
		arg.BotID,
		arg.Ts,
		arg.CpuPct,
		arg.MemoryBytes,
		arg.DiskBytes,
		arg.NetRx,
		arg.NetTx,
	)
	return err
}
