// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nodes.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countNodeBots = `-- name: CountNodeBots :one
SELECT count(*)::int FROM bots WHERE node_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountNodeBots(ctx context.Context, nodeID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countNodeBots, nodeID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createNode = `-- name: CreateNode :one
INSERT INTO nodes (name, region, token_hash, memory_mb, cpu_millicores, disk_mb, overcommit)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, region, token_hash, memory_mb, cpu_millicores, disk_mb, overcommit, maintenance, agent_version, info, runsc, last_seen_at, created_at
`

type CreateNodeParams struct {
	Name          string
	Region        string
	TokenHash     []byte
	MemoryMb      int32
	CpuMillicores int32
	DiskMb        int32
	Overcommit    float64
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, createNode,
		arg.Name,
		arg.Region,
		arg.TokenHash,
		arg.MemoryMb,
		arg.CpuMillicores,
		arg.DiskMb,
		arg.Overcommit,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Region,
		&i.TokenHash,
		&i.MemoryMb,
		&i.CpuMillicores,
		&i.DiskMb,
		&i.Overcommit,
		&i.Maintenance,
		&i.AgentVersion,
		&i.Info,
		&i.Runsc,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteNode = `-- name: DeleteNode :exec
DELETE FROM nodes WHERE id = $1
`

func (q *Queries) DeleteNode(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteNode, id)
	return err
}

const getNode = `-- name: GetNode :one
SELECT id, name, region, token_hash, memory_mb, cpu_millicores, disk_mb, overcommit, maintenance, agent_version, info, runsc, last_seen_at, created_at FROM nodes WHERE id = $1
`

func (q *Queries) GetNode(ctx context.Context, id uuid.UUID) (Node, error) {
	row := q.db.QueryRow(ctx, getNode, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Region,
		&i.TokenHash,
		&i.MemoryMb,
		&i.CpuMillicores,
		&i.DiskMb,
		&i.Overcommit,
		&i.Maintenance,
		&i.AgentVersion,
		&i.Info,
		&i.Runsc,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const getNodeByTokenHash = `-- name: GetNodeByTokenHash :one
SELECT id, name, region, token_hash, memory_mb, cpu_millicores, disk_mb, overcommit, maintenance, agent_version, info, runsc, last_seen_at, created_at FROM nodes WHERE token_hash = $1
`

func (q *Queries) GetNodeByTokenHash(ctx context.Context, tokenHash []byte) (Node, error) {
	row := q.db.QueryRow(ctx, getNodeByTokenHash, tokenHash)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Region,
		&i.TokenHash,
		&i.MemoryMb,
		&i.CpuMillicores,
		&i.DiskMb,
		&i.Overcommit,
		&i.Maintenance,
		&i.AgentVersion,
		&i.Info,
		&i.Runsc,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const listNodes = `-- name: ListNodes :many
SELECT n.id, n.name, n.region, n.token_hash, n.memory_mb, n.cpu_millicores, n.disk_mb, n.overcommit, n.maintenance, n.agent_version, n.info, n.runsc, n.last_seen_at, n.created_at,
       count(b.id)::int                             AS bot_count,
       coalesce(sum(b.memory_mb), 0)::int           AS allocated_memory_mb,
       coalesce(sum(b.cpu_millicores), 0)::int      AS allocated_cpu_millicores,
       coalesce(sum(b.disk_mb), 0)::int             AS allocated_disk_mb
FROM nodes n
LEFT JOIN bots b ON b.node_id = n.id AND b.deleted_at IS NULL
GROUP BY n.id
ORDER BY n.name
`

type ListNodesRow struct {
	ID                     uuid.UUID
	Name                   string
	Region                 string
	TokenHash              []byte
	MemoryMb               int32
	CpuMillicores          int32
	DiskMb                 int32
	Overcommit             float64
	Maintenance            bool
	AgentVersion           string
	Info                   []byte
	Runsc                  bool
	LastSeenAt             *time.Time
	CreatedAt              time.Time
	BotCount               int32
	AllocatedMemoryMb      int32
	AllocatedCpuMillicores int32
	AllocatedDiskMb        int32
}

func (q *Queries) ListNodes(ctx context.Context) ([]ListNodesRow, error) {
	rows, err := q.db.Query(ctx, listNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNodesRow
	for rows.Next() {
		var i ListNodesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Region,
			&i.TokenHash,
			&i.MemoryMb,
			&i.CpuMillicores,
			&i.DiskMb,
			&i.Overcommit,
			&i.Maintenance,
			&i.AgentVersion,
			&i.Info,
			&i.Runsc,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.BotCount,
			&i.AllocatedMemoryMb,
			&i.AllocatedCpuMillicores,
			&i.AllocatedDiskMb,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const placementCandidates = `-- name: PlacementCandidates :many
SELECT n.id, n.memory_mb, n.cpu_millicores, n.disk_mb, n.overcommit, n.runsc,
       coalesce((SELECT sum(b.memory_mb) FROM bots b WHERE b.node_id = n.id AND b.deleted_at IS NULL), 0)::int      AS used_memory_mb,
       coalesce((SELECT sum(b.cpu_millicores) FROM bots b WHERE b.node_id = n.id AND b.deleted_at IS NULL), 0)::int AS used_cpu_millicores,
       coalesce((SELECT sum(b.disk_mb) FROM bots b WHERE b.node_id = n.id AND b.deleted_at IS NULL), 0)::int        AS used_disk_mb
FROM nodes n
WHERE NOT n.maintenance
  AND n.last_seen_at > now() - interval '45 seconds'
  AND (NOT $1::bool OR n.runsc)
ORDER BY n.id
FOR UPDATE OF n
`

type PlacementCandidatesRow struct {
	ID                uuid.UUID
	MemoryMb          int32
	CpuMillicores     int32
	DiskMb            int32
	Overcommit        float64
	Runsc             bool
	UsedMemoryMb      int32
	UsedCpuMillicores int32
	UsedDiskMb        int32
}

// Candidates for placing a bot, most free memory first. Locks the rows so concurrent placements
// serialise per node. Online means seen within the last 45 seconds.
func (q *Queries) PlacementCandidates(ctx context.Context, needRunsc bool) ([]PlacementCandidatesRow, error) {
	rows, err := q.db.Query(ctx, placementCandidates, needRunsc)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlacementCandidatesRow
	for rows.Next() {
		var i PlacementCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.MemoryMb,
			&i.CpuMillicores,
			&i.DiskMb,
			&i.Overcommit,
			&i.Runsc,
			&i.UsedMemoryMb,
			&i.UsedCpuMillicores,
			&i.UsedDiskMb,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rotateNodeToken = `-- name: RotateNodeToken :exec
UPDATE nodes SET token_hash = $2 WHERE id = $1
`

type RotateNodeTokenParams struct {
	ID        uuid.UUID
	TokenHash []byte
}

func (q *Queries) RotateNodeToken(ctx context.Context, arg RotateNodeTokenParams) error {
	_, err := q.db.Exec(ctx, rotateNodeToken, arg.ID, arg.TokenHash)
	return err
}

const touchNode = `-- name: TouchNode :exec
UPDATE nodes SET last_seen_at = now() WHERE id = $1
`

func (q *Queries) TouchNode(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchNode, id)
	return err
}

const updateNode = `-- name: UpdateNode :one
UPDATE nodes SET name = $2, region = $3, memory_mb = $4, cpu_millicores = $5, disk_mb = $6,
                 overcommit = $7, maintenance = $8
WHERE id = $1
RETURNING id, name, region, token_hash, memory_mb, cpu_millicores, disk_mb, overcommit, maintenance, agent_version, info, runsc, last_seen_at, created_at
`

type UpdateNodeParams struct {
	ID            uuid.UUID
	Name          string
	Region        string
	MemoryMb      int32
	CpuMillicores int32
	DiskMb        int32
	Overcommit    float64
	Maintenance   bool
}

func (q *Queries) UpdateNode(ctx context.Context, arg UpdateNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, updateNode,
		arg.ID,
		arg.Name,
		arg.Region,
		arg.MemoryMb,
		arg.CpuMillicores,
		arg.DiskMb,
		arg.Overcommit,
		arg.Maintenance,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Region,
		&i.TokenHash,
		&i.MemoryMb,
		&i.CpuMillicores,
		&i.DiskMb,
		&i.Overcommit,
		&i.Maintenance,
		&i.AgentVersion,
		&i.Info,
		&i.Runsc,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateNodeHello = `-- name: UpdateNodeHello :exec
UPDATE nodes SET agent_version = $2, info = $3, runsc = $4, last_seen_at = now() WHERE id = $1
`

type UpdateNodeHelloParams struct {
	ID           uuid.UUID
	AgentVersion string
	Info         []byte
	Runsc        bool
}

func (q *Queries) UpdateNodeHello(ctx context.Context, arg UpdateNodeHelloParams) error {
	_, err := q.db.Exec(ctx, updateNodeHello,
		arg.ID,
		arg.AgentVersion,
		arg.Info,
		arg.Runsc,
	)
	return err
}
