// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plans.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const archivePlan = `-- name: ArchivePlan :exec
UPDATE plans SET archived_at = now() WHERE id = $1
`

func (q *Queries) ArchivePlan(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, archivePlan, id)
	return err
}

const createPlan = `-- name: CreatePlan :one
INSERT INTO plans (slug, name, max_bots, memory_mb, cpu_millicores, disk_mb, pids_max, hardened, templates)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, slug, name, max_bots, memory_mb, cpu_millicores, disk_mb, pids_max, hardened, templates, archived_at, created_at
`

type CreatePlanParams struct {
	Slug          string
	Name          string
	MaxBots       int32
	MemoryMb      int32
	CpuMillicores int32
	DiskMb        int32
	PidsMax       int32
	Hardened      bool
	Templates     []string
}

func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, createPlan,
		arg.Slug,
		arg.Name,
		arg.MaxBots,
		arg.MemoryMb,
		arg.CpuMillicores,
		arg.DiskMb,
		arg.PidsMax,
		arg.Hardened,
		arg.Templates,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.MaxBots,
		&i.MemoryMb,
		&i.CpuMillicores,
		&i.DiskMb,
		&i.PidsMax,
		&i.Hardened,
		&i.Templates,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPlan = `-- name: GetPlan :one
SELECT id, slug, name, max_bots, memory_mb, cpu_millicores, disk_mb, pids_max, hardened, templates, archived_at, created_at FROM plans WHERE id = $1
`

func (q *Queries) GetPlan(ctx context.Context, id uuid.UUID) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlan, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.MaxBots,
		&i.MemoryMb,
		&i.CpuMillicores,
		&i.DiskMb,
		&i.PidsMax,
		&i.Hardened,
		&i.Templates,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listPlans = `-- name: ListPlans :many
SELECT p.id, p.slug, p.name, p.max_bots, p.memory_mb, p.cpu_millicores, p.disk_mb, p.pids_max, p.hardened, p.templates, p.archived_at, p.created_at,
       (SELECT count(*) FROM subscriptions s WHERE s.plan_id = p.id AND s.status <> 'terminated')::int AS subscription_count
FROM plans p
WHERE p.archived_at IS NULL
ORDER BY p.memory_mb, p.name
`

type ListPlansRow struct {
	ID                uuid.UUID
	Slug              string
	Name              string
	MaxBots           int32
	MemoryMb          int32
	CpuMillicores     int32
	DiskMb            int32
	PidsMax           int32
	Hardened          bool
	Templates         []string
	ArchivedAt        *time.Time
	CreatedAt         time.Time
	SubscriptionCount int32
}

func (q *Queries) ListPlans(ctx context.Context) ([]ListPlansRow, error) {
	rows, err := q.db.Query(ctx, listPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlansRow
	for rows.Next() {
		var i ListPlansRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.MaxBots,
			&i.MemoryMb,
			&i.CpuMillicores,
			&i.DiskMb,
			&i.PidsMax,
			&i.Hardened,
			&i.Templates,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.SubscriptionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlan = `-- name: UpdatePlan :one
UPDATE plans SET name = $2, max_bots = $3, memory_mb = $4, cpu_millicores = $5, disk_mb = $6,
                 pids_max = $7, hardened = $8, templates = $9
WHERE id = $1 AND archived_at IS NULL
RETURNING id, slug, name, max_bots, memory_mb, cpu_millicores, disk_mb, pids_max, hardened, templates, archived_at, created_at
`

type UpdatePlanParams struct {
	ID            uuid.UUID
	Name          string
	MaxBots       int32
	MemoryMb      int32
	CpuMillicores int32
	DiskMb        int32
	PidsMax       int32
	Hardened      bool
	Templates     []string
}

func (q *Queries) UpdatePlan(ctx context.Context, arg UpdatePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, updatePlan,
		arg.ID,
		arg.Name,
		arg.MaxBots,
		arg.MemoryMb,
		arg.CpuMillicores,
		arg.DiskMb,
		arg.PidsMax,
		arg.Hardened,
		arg.Templates,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.MaxBots,
		&i.MemoryMb,
		&i.CpuMillicores,
		&i.DiskMb,
		&i.PidsMax,
		&i.Hardened,
		&i.Templates,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}
