// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscriptions.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (user_id, plan_id, external_id) VALUES ($1, $2, $3) RETURNING id, user_id, plan_id, status, external_id, created_at, max_bots, memory_mb, cpu_millicores, disk_mb, pids_max, note
`

type CreateSubscriptionParams struct {
	UserID     uuid.UUID
	PlanID     uuid.UUID
	ExternalID *string
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription, arg.UserID, arg.PlanID, arg.ExternalID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Status,
		&i.ExternalID,
		&i.CreatedAt,
		&i.MaxBots,
		&i.MemoryMb,
		&i.CpuMillicores,
		&i.DiskMb,
		&i.PidsMax,
		&i.Note,
	)
	return i, err
}

const getSubscription = `-- name: GetSubscription :one
SELECT id, user_id, plan_id, status, external_id, created_at, max_bots, memory_mb, cpu_millicores, disk_mb, pids_max, note FROM subscriptions WHERE id = $1
`

func (q *Queries) GetSubscription(ctx context.Context, id uuid.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscription, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Status,
		&i.ExternalID,
		&i.CreatedAt,
		&i.MaxBots,
		&i.MemoryMb,
		&i.CpuMillicores,
		&i.DiskMb,
		&i.PidsMax,
		&i.Note,
	)
	return i, err
}

const getSubscriptionForUpdate = `-- name: GetSubscriptionForUpdate :one
SELECT id, user_id, plan_id, status, external_id, created_at, max_bots, memory_mb, cpu_millicores, disk_mb, pids_max, note FROM subscriptions WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetSubscriptionForUpdate(ctx context.Context, id uuid.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionForUpdate, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Status,
		&i.ExternalID,
		&i.CreatedAt,
		&i.MaxBots,
		&i.MemoryMb,
		&i.CpuMillicores,
		&i.DiskMb,
		&i.PidsMax,
		&i.Note,
	)
	return i, err
}

const listSubscriptionsForUser = `-- name: ListSubscriptionsForUser :many
SELECT subscriptions.id, subscriptions.user_id, subscriptions.plan_id, subscriptions.status, subscriptions.external_id, subscriptions.created_at, subscriptions.max_bots, subscriptions.memory_mb, subscriptions.cpu_millicores, subscriptions.disk_mb, subscriptions.pids_max, subscriptions.note, plans.id, plans.slug, plans.name, plans.max_bots, plans.memory_mb, plans.cpu_millicores, plans.disk_mb, plans.pids_max, plans.hardened, plans.templates, plans.archived_at, plans.created_at,
       coalesce(sum(b.memory_mb) FILTER (WHERE b.id IS NOT NULL), 0)::int      AS used_memory_mb,
       coalesce(sum(b.cpu_millicores) FILTER (WHERE b.id IS NOT NULL), 0)::int AS used_cpu_millicores,
       coalesce(sum(b.disk_mb) FILTER (WHERE b.id IS NOT NULL), 0)::int        AS used_disk_mb,
       count(b.id)::int                                                       AS used_bots
FROM subscriptions
JOIN plans ON plans.id = subscriptions.plan_id
LEFT JOIN bots b ON b.subscription_id = subscriptions.id AND b.deleted_at IS NULL
WHERE subscriptions.user_id = $1 AND subscriptions.status <> 'terminated'
GROUP BY subscriptions.id, plans.id
ORDER BY subscriptions.created_at
`

type ListSubscriptionsForUserRow struct {
	Subscription      Subscription
	Plan              Plan
	UsedMemoryMb      int32
	UsedCpuMillicores int32
	UsedDiskMb        int32
	UsedBots          int32
}

func (q *Queries) ListSubscriptionsForUser(ctx context.Context, userID uuid.UUID) ([]ListSubscriptionsForUserRow, error) {
	rows, err := q.db.Query(ctx, listSubscriptionsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubscriptionsForUserRow
	for rows.Next() {
		var i ListSubscriptionsForUserRow
		if err := rows.Scan(
			&i.Subscription.ID,
			&i.Subscription.UserID,
			&i.Subscription.PlanID,
			&i.Subscription.Status,
			&i.Subscription.ExternalID,
			&i.Subscription.CreatedAt,
			&i.Subscription.MaxBots,
			&i.Subscription.MemoryMb,
			&i.Subscription.CpuMillicores,
			&i.Subscription.DiskMb,
			&i.Subscription.PidsMax,
			&i.Subscription.Note,
			&i.Plan.ID,
			&i.Plan.Slug,
			&i.Plan.Name,
			&i.Plan.MaxBots,
			&i.Plan.MemoryMb,
			&i.Plan.CpuMillicores,
			&i.Plan.DiskMb,
			&i.Plan.PidsMax,
			&i.Plan.Hardened,
			&i.Plan.Templates,
			&i.Plan.ArchivedAt,
			&i.Plan.CreatedAt,
			&i.UsedMemoryMb,
			&i.UsedCpuMillicores,
			&i.UsedDiskMb,
			&i.UsedBots,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSubscriptionOverrides = `-- name: SetSubscriptionOverrides :one
UPDATE subscriptions
SET max_bots = $2, memory_mb = $3, cpu_millicores = $4, disk_mb = $5, pids_max = $6, note = $7
WHERE id = $1
RETURNING id, user_id, plan_id, status, external_id, created_at, max_bots, memory_mb, cpu_millicores, disk_mb, pids_max, note
`

type SetSubscriptionOverridesParams struct {
	ID            uuid.UUID
	MaxBots       *int32
	MemoryMb      *int32
	CpuMillicores *int32
	DiskMb        *int32
	PidsMax       *int32
	Note          string
}

func (q *Queries) SetSubscriptionOverrides(ctx context.Context, arg SetSubscriptionOverridesParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, setSubscriptionOverrides,
		arg.ID,
		arg.MaxBots,
		arg.MemoryMb,
		arg.CpuMillicores,
		arg.DiskMb,
		arg.PidsMax,
		arg.Note,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Status,
		&i.ExternalID,
		&i.CreatedAt,
		&i.MaxBots,
		&i.MemoryMb,
		&i.CpuMillicores,
		&i.DiskMb,
		&i.PidsMax,
		&i.Note,
	)
	return i, err
}

const setSubscriptionPlan = `-- name: SetSubscriptionPlan :one
UPDATE subscriptions SET plan_id = $2 WHERE id = $1 RETURNING id, user_id, plan_id, status, external_id, created_at, max_bots, memory_mb, cpu_millicores, disk_mb, pids_max, note
`

type SetSubscriptionPlanParams struct {
	ID     uuid.UUID
	PlanID uuid.UUID
}

func (q *Queries) SetSubscriptionPlan(ctx context.Context, arg SetSubscriptionPlanParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, setSubscriptionPlan, arg.ID, arg.PlanID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Status,
		&i.ExternalID,
		&i.CreatedAt,
		&i.MaxBots,
		&i.MemoryMb,
		&i.CpuMillicores,
		&i.DiskMb,
		&i.PidsMax,
		&i.Note,
	)
	return i, err
}

const setSubscriptionStatus = `-- name: SetSubscriptionStatus :one
UPDATE subscriptions SET status = $2 WHERE id = $1 RETURNING id, user_id, plan_id, status, external_id, created_at, max_bots, memory_mb, cpu_millicores, disk_mb, pids_max, note
`

type SetSubscriptionStatusParams struct {
	ID     uuid.UUID
	Status SubscriptionStatus
}

func (q *Queries) SetSubscriptionStatus(ctx context.Context, arg SetSubscriptionStatusParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, setSubscriptionStatus, arg.ID, arg.Status)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Status,
		&i.ExternalID,
		&i.CreatedAt,
		&i.MaxBots,
		&i.MemoryMb,
		&i.CpuMillicores,
		&i.DiskMb,
		&i.PidsMax,
		&i.Note,
	)
	return i, err
}

const subscriptionUsage = `-- name: SubscriptionUsage :one
SELECT count(*)::int                           AS bots,
       coalesce(sum(memory_mb), 0)::int        AS memory_mb,
       coalesce(sum(cpu_millicores), 0)::int   AS cpu_millicores,
       coalesce(sum(disk_mb), 0)::int          AS disk_mb
FROM bots
WHERE subscription_id = $1 AND deleted_at IS NULL AND id <> $2
`

type SubscriptionUsageParams struct {
	SubscriptionID uuid.UUID
	ExcludeBotID   uuid.UUID
}

type SubscriptionUsageRow struct {
	Bots          int32
	MemoryMb      int32
	CpuMillicores int32
	DiskMb        int32
}

func (q *Queries) SubscriptionUsage(ctx context.Context, arg SubscriptionUsageParams) (SubscriptionUsageRow, error) {
	row := q.db.QueryRow(ctx, subscriptionUsage, arg.SubscriptionID, arg.ExcludeBotID)
	var i SubscriptionUsageRow
	err := row.Scan(
		&i.Bots,
		&i.MemoryMb,
		&i.CpuMillicores,
		&i.DiskMb,
	)
	return i, err
}
