// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhooks.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createWebhookDelivery = `-- name: CreateWebhookDelivery :one
INSERT INTO webhook_deliveries (endpoint_id, event_id, event_type, payload) VALUES ($1, $2, $3, $4) RETURNING id, endpoint_id, event_id, event_type, payload, status, attempts, last_status_code, last_error, created_at, delivered_at
`

type CreateWebhookDeliveryParams struct {
	EndpointID uuid.UUID
	EventID    uuid.UUID
	EventType  string
	Payload    []byte
}

func (q *Queries) CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, createWebhookDelivery,
		arg.EndpointID,
		arg.EventID,
		arg.EventType,
		arg.Payload,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.EventID,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.LastStatusCode,
		&i.LastError,
		&i.CreatedAt,
		&i.DeliveredAt,
	)
	return i, err
}

const createWebhookEndpoint = `-- name: CreateWebhookEndpoint :one
INSERT INTO webhook_endpoints (url, description, secret_enc, events) VALUES ($1, $2, $3, $4) RETURNING id, url, description, secret_enc, events, enabled, created_at
`

type CreateWebhookEndpointParams struct {
	Url         string
	Description string
	SecretEnc   []byte
	Events      []string
}

func (q *Queries) CreateWebhookEndpoint(ctx context.Context, arg CreateWebhookEndpointParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, createWebhookEndpoint,
		arg.Url,
		arg.Description,
		arg.SecretEnc,
		arg.Events,
	)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Description,
		&i.SecretEnc,
		&i.Events,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWebhookEndpoint = `-- name: DeleteWebhookEndpoint :exec
DELETE FROM webhook_endpoints WHERE id = $1
`

func (q *Queries) DeleteWebhookEndpoint(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWebhookEndpoint, id)
	return err
}

const endpointsForEvent = `-- name: EndpointsForEvent :many
SELECT id, url, description, secret_enc, events, enabled, created_at FROM webhook_endpoints WHERE enabled AND (events = '{}' OR $1::text = ANY (events))
`

func (q *Queries) EndpointsForEvent(ctx context.Context, eventType string) ([]WebhookEndpoint, error) {
	rows, err := q.db.Query(ctx, endpointsForEvent, eventType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookEndpoint
	for rows.Next() {
		var i WebhookEndpoint
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Description,
			&i.SecretEnc,
			&i.Events,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWebhookDelivery = `-- name: GetWebhookDelivery :one
SELECT id, endpoint_id, event_id, event_type, payload, status, attempts, last_status_code, last_error, created_at, delivered_at FROM webhook_deliveries WHERE id = $1
`

func (q *Queries) GetWebhookDelivery(ctx context.Context, id uuid.UUID) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, getWebhookDelivery, id)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.EventID,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.LastStatusCode,
		&i.LastError,
		&i.CreatedAt,
		&i.DeliveredAt,
	)
	return i, err
}

const getWebhookEndpoint = `-- name: GetWebhookEndpoint :one
SELECT id, url, description, secret_enc, events, enabled, created_at FROM webhook_endpoints WHERE id = $1
`

func (q *Queries) GetWebhookEndpoint(ctx context.Context, id uuid.UUID) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, getWebhookEndpoint, id)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Description,
		&i.SecretEnc,
		&i.Events,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const listWebhookDeliveries = `-- name: ListWebhookDeliveries :many
SELECT id, endpoint_id, event_id, event_type, payload, status, attempts, last_status_code, last_error, created_at, delivered_at FROM webhook_deliveries WHERE endpoint_id = $1 ORDER BY created_at DESC LIMIT 50
`

func (q *Queries) ListWebhookDeliveries(ctx context.Context, endpointID uuid.UUID) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listWebhookDeliveries, endpointID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookDelivery
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.EndpointID,
			&i.EventID,
			&i.EventType,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.LastStatusCode,
			&i.LastError,
			&i.CreatedAt,
			&i.DeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookEndpoints = `-- name: ListWebhookEndpoints :many
SELECT e.id, e.url, e.description, e.secret_enc, e.events, e.enabled, e.created_at,
       (SELECT count(*) FROM webhook_deliveries d WHERE d.endpoint_id = e.id AND d.status = 'failed' AND d.created_at > now() - interval '24 hours')::int AS failed_24h
FROM webhook_endpoints e
ORDER BY e.created_at
`

type ListWebhookEndpointsRow struct {
	ID          uuid.UUID
	Url         string
	Description string
	SecretEnc   []byte
	Events      []string
	Enabled     bool
	CreatedAt   time.Time
	Failed24h   int32
}

func (q *Queries) ListWebhookEndpoints(ctx context.Context) ([]ListWebhookEndpointsRow, error) {
	rows, err := q.db.Query(ctx, listWebhookEndpoints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWebhookEndpointsRow
	for rows.Next() {
		var i ListWebhookEndpointsRow
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Description,
			&i.SecretEnc,
			&i.Events,
			&i.Enabled,
			&i.CreatedAt,
			&i.Failed24h,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordDeliveryAttempt = `-- name: RecordDeliveryAttempt :exec
UPDATE webhook_deliveries
SET attempts = attempts + 1, status = $1::webhook_delivery_status, last_status_code = $2,
    last_error = $3, delivered_at = CASE WHEN $1::webhook_delivery_status = 'delivered' THEN now() ELSE delivered_at END
WHERE id = $4
`

type RecordDeliveryAttemptParams struct {
	Status         WebhookDeliveryStatus
	LastStatusCode *int32
	LastError      string
	ID             uuid.UUID
}

func (q *Queries) RecordDeliveryAttempt(ctx context.Context, arg RecordDeliveryAttemptParams) error {
	_, err := q.db.Exec(ctx, recordDeliveryAttempt,
		arg.Status,
		arg.LastStatusCode,
		arg.LastError,
		arg.ID,
	)
	return err
}

const resetDelivery = `-- name: ResetDelivery :exec
UPDATE webhook_deliveries SET status = 'pending' WHERE id = $1
`

func (q *Queries) ResetDelivery(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetDelivery, id)
	return err
}

const updateWebhookEndpoint = `-- name: UpdateWebhookEndpoint :one
UPDATE webhook_endpoints SET url = $2, description = $3, events = $4, enabled = $5 WHERE id = $1 RETURNING id, url, description, secret_enc, events, enabled, created_at
`

type UpdateWebhookEndpointParams struct {
	ID          uuid.UUID
	Url         string
	Description string
	Events      []string
	Enabled     bool
}

func (q *Queries) UpdateWebhookEndpoint(ctx context.Context, arg UpdateWebhookEndpointParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, updateWebhookEndpoint,
		arg.ID,
		arg.Url,
		arg.Description,
		arg.Events,
		arg.Enabled,
	)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Description,
		&i.SecretEnc,
		&i.Events,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}
